### ISSUE TITLE
Pluralsight: Bundling - Demo Create App Entry Point

### ISSUE THREAD

**Issue by viamyeye** [coryhouse/javascript-development-environment#14]
Hi Cory,

When running npm start, after seeing "(+) No known vulnerabilities found" i'm seeing the following output:

\pluralsight-js-dev-env\webpack.config.dev.js:2
import path from 'path';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at loader (\pluralsight-js-dev-env\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (\Pluralsight\pluralsight-js-dev-env\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

What am I doing wrong?

**Comment by coryhouse** [comment]
It sounds like Babel isn't configured to transpile your code. Please download the final course exercise from the course page. Does the final exercise run for you?

**Comment by coryhouse** [comment]
Also, be sure to check this list: https://github.com/coryhouse/javascript-development-environment#having-issues-try-these-things-first

**Comment by viamyeye** [comment]
Cheers Cory, i'll give your suggestions a go and let you know how I get on.

**Comment by viamyeye** [comment]
Resolved! Step 3 of https://github.com/coryhouse/javascript-development-environment#having-issues-try-these-things-first. I had my .babelrc file in my buildScipts dir instread of root. Thanks for the assistance and your Pluralsight Courses, i'm learning lots. Cheers from over the pond.

**Comment by coryhouse** [comment]
Great to hear!
