### ISSUE TITLE
Getting unhandled error event on npm start

### ISSUE THREAD

**Issue by jaredwilli** [coryhouse/javascript-development-environment#15]
Just cloned and installed deps and when i run npm start I get this...

```> javascript-development-environment@1.0.0 generate-mock-data /Users/jaredw/Sites/_play/javascript-development-environment
> babel-node buildScripts/generateMockData


events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (/Users/jaredw/Sites/_play/javascript-development-environment/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/jaredw/Sites/_play/javascript-development-environment/buildScripts/srcServer.js:31:5)
    at Module._compile (module.js:570:32)
    at loader (/Users/jaredw/Sites/_play/javascript-development-environment/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jaredw/Sites/_play/javascript-development-environment/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at /Users/jaredw/Sites/_play/javascript-development-environment/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/Users/jaredw/Sites/_play/javascript-development-environment/node_modules/babel-cli/lib/_babel-node.js:160:7)

**Comment by coryhouse** [comment]
That means port 3000 is already in use - likely because you already have an instance of this project running in a different window. :)
