### ISSUE TITLE
node_modules\open\lib\open.js:62 return s.replace(/"/g, '\\\"'); TypeError: s.replace is not a function

### ISSUE THREAD

**Issue by piatkiewicz** [coryhouse/javascript-development-environment#35]
Hi, I really like the course, but encountered a problem almost on beginning. 
When running `node buildScripts/srcServer.js` from module 5, clip 3 (_Development Web Server : Demo: Set up Express_) I get this error:
```
C:\projects\js-environment>node buildScripts/srcServer.js
C:\projects\js-environment\node_modules\open\lib\open.js:62
  return s.replace(/"/g, '\\\"');
           ^

TypeError: s.replace is not a function
    at escape (C:\projects\js-environment\node_modules\open\lib\open.js:62:12)
    at open (C:\projects\js-environment\node_modules\open\lib\open.js:40:31)
    at Server.<anonymous> (C:\projects\js-environment\buildScripts\srcServer.js:17:9)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitListeningNT (net.js:1313:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Code here: https://github.com/piatkiewicz/js-environment/tree/openjs62-error
Node version is `v10.16.0`

Could someone help me with that?

**Comment by coryhouse** [comment]
Can you please post on the course discussion so others can benefit from our dialogue?

**Comment by piatkiewicz** [comment]
Sure, just did it, thanks.
